version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo

phases:
  pre_build:
    on-failure: ABORT
    commands:
    - COMMIT=`git rev-parse --short HEAD`
    - BRANCH=`git symbolic-ref -q --short HEAD || git name-rev $(git rev-parse --short HEAD) | cut -d' ' -f2 || echo ''`
    - TAG=`git describe --tags --exact-match 2> /dev/null || echo ''`
    - BRANCHTAG=`git describe --tags --exact-match 2> /dev/null || git symbolic-ref -q --short HEAD || git name-rev $(git rev-parse --short HEAD) | cut -d' ' -f2 || git rev-parse --short HEAD`
    - echo "Branchtag ${BRANCHTAG}; COMMITDATE=${COMMITDATE}; REPONAME=${REPONAME}; BRANCHNAME=${BRANCHNAME}"

    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_REGISTRY}
    - SSM_ROOT_PATH=/uc3/mrt/dev/
    - DATAPATH=`aws ssm get-parameter --name /uc3/mrt/dev/integ-tests/data-path --query "Parameter.Value" --output text`
    - DATAURL="https://merritt.uc3dev.cdlib.org/${DATAPATH}"

  build:
    on-failure: ABORT
    commands:
    - |
      if ! [[ `aws s3 ls s3://${S3CFBUCKET}/${DATAPATH}` ]]
      then
        ruby makefile.rb data.1k  1_000
        ruby makefile.rb data.1m  1_000_000
        ruby makefile.rb data.50m 50_000_000
        ruby makefile.rb data.1g  1_000_000_000
        for file in /tmp/datapath/data*
        do
          aws s3 cp $file s3://${S3CFBUCKET}/${DATAPATH}/
        done
      fi

    - |
      docker build --push --quiet \
        -t ${ECR_REGISTRY}/${REPONAME} \
        .
    - |
      docker build --push --quiet \
        -t ${ECR_REGISTRY}/mrt-it-chrome \
        chrome-driver || echo "dockerhub rate limiting may occur"
   
    - docker-compose up -d chrome
    - |
      if [ "$INTEG_TEST_ENV" != "none" ]
      then
        docker-compose run --rm \
          -e DATAURL=$DATAURL \
          -e INTEG_TEST_ENV=$INTEG_TEST_ENV \
          -e INGEST_FILES=$INGEST_FILES \
          -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI \
          -e SSM_ROOT_PATH=$SSM_ROOT_PATH mrt-integ-tests
      fi
    - docker-compose down
