#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.9'
networks:
  mynet:
volumes:
  downloads:
services:
  mrt-integ-tests:
    container_name: mrt-integ-tests
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mrt-integ-tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./config/test_config.yml
      target: /config/test_config.yml
    - downloads:/tmp/downloads
    environment:
      #uncomment the following when running rspec with a non-headless chrome
      CHROME_URL: http://chrome:4444/wd/hub
      SSM_ROOT_PATH: ${SSM_ROOT_PATH:-/uc3/mrt/dev/}
      HOSTNAME: ${HOSTNAME}.cdlib.org
    stdin_open: true
    tty: true
    networks:
      mynet:
    depends_on:
    - chrome
  chrome:
    container_name: chrome
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mrt-it-chrome
    # build a docker image that will make the downloads folder accessible (permissions) as a volume mount
    build:
      context: chrome-driver
      dockerfile: Dockerfile
    shm_size: '2gb'
    networks:
      mynet:
    volumes:
    - /dev/shm:/dev/shm
    - downloads:/home/seluser/Downloads
