#*********************************************************************
#   Copyright 2019 Regents of the University of California
#   All rights reserved
#*********************************************************************
version: '3.7'
networks:
  mynet:
services:
  mrt-integ-tests:
    container_name: mrt-integ-tests
    image: cdluc3/mrt-integ-tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./config/test_config.yml
      target: /config/test_config.yml
    environment:
      CHROME_URL: http://chrome:4444/wd/hub
    stdin_open: true
    tty: true
    networks:
      mynet:
    depends_on:
    - chrome
  chrome:
    container_name: chrome
    image: selenium/standalone-chrome
    networks:
      mynet:
