# frozen_string_literal: true

source 'https://rubygems.org'
gem 'base64'
gem 'capybara'
gem 'capybara-webmock'
gem 'colorize'
gem 'rspec'
# gem 'webdrivers'
# gem 'chromedriver-helper'
gem 'byebug'
gem 'nokogiri'
gem 'rubocop'
gem 'selenium-webdriver', '>= 4.16'
gem 'uc3-ssm', '0.3.10', git: 'https://github.com/CDLUC3/uc3-ssm.git', branch: 'main'
